
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - stack.env
    networks:
      - apps

networks:
  apps:
    external: true